### ISSUE TITLE
mknod: /dev/net/tun: Operation not permitted (podman)

### ISSUE THREAD

**Issue by xscd** [ntkme/boringtun#34]
Can't run this container with podman.
```
podman run -d \
  --cap-add MKNOD \
  --cap-add NET_ADMIN \
  --cap-add NET_RAW \
  --publish 51820:51820/udp \
  --volume /etc/wireguard/wg0.conf:/etc/wireguard/wg0.conf \
  ghcr.io/ntkme/boringtun:edge wg0
```

In logs says ```mknod: /dev/net/tun: Operation not permitted```

**Comment by ntkme** [comment]
Did you run podman in rootless mode initially? Some capabilities won’t work in rootless mode.

The poll error during startup can be safely ignored.
