### ISSUE TITLE
How do I create a config file

### ISSUE THREAD

**Issue by TarekSalama** [ntkme/boringtun#37]
Sorry for my ignorance, but if I use this docker image, how do I go around setting up a configuration file that I can use on macOS or Windows with the official WireGuard client?

Thanks!

**Comment by TarekSalama** [comment]
So does the docker image setup a working WireGuard (BoringTun) VPN and all I have to do is run the `wg` or `wg-quick` command? 
Again sorry for my ignorance but all my previous interaction with WireGuard and VPNs in general was through scripts like PiVPN and the likes.

**Comment by ntkme** [comment]
This container runs a modified wg-quick in order to start boringtun as a foreground process. You just need a config file that works for wg-quick and place it at right location.
